:toc:
:toclevels: 5
:toc-placement!:
:source-highlighter: highlight.js
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= QADO Question Answering Dataset RDFizer

This tool provides a web service to convert particular question answering datasets (represented in JSON format) into https://www.w3.org/TR/turtle/[RDF Turtle]. 
It uses the https://github.com/WSE-research/QADO-question-answering-dataset-RDFizer/blob/main/app/ontology/qa-benchmark-ontology.ttl[Question Answering Dataset Ontology (QADO)] to represent the data in RDF.

toc::[]

== Setup service

=== Configuration
This service needs a running instance of https://github.com/WSE-research/QADO-RML-Applicator[QADO RML Applicator].
The host of a instance, e. g. http://localhost:8000, has to be
provided by setting the environment variable
`RML_APPLICATOR_HOST`.

=== Using Gradle

To run the service locally run `./gradlew run`.

=== Using Docker

Otherwise, you can set up a Docker image running the service by pulling the following
image:

[source,bash]
----
docker pull bigoli98/rdfizer:latest
----

Alternatively you can build the Docker image from source.
To start a Docker container use the following command:

[source,shell]
----
docker run -d --env RML_APPLICATOR_HOST="YOUR RML APPLICATOR HOST" -p "$EXTERNAL_PORT:8080" bigoli98/rdfizer:latest
----

== Accessing the service
=== Basic UI
This service provides a basic UI at `$HOST:$PORT/` where you can
transform a dataset and view the results directly in the
web browser.

=== API endpoint
To transform a JSON file to RDF perform a `POST`-Request at `$HOST:$PORT/json2rdf`
with a JSON payload of the following structure:

[source,json]
----
{
  "filePath": "URL of the JSON file",
  "format": "Mapping file name",
  "label": "Name for the generated RDF triples",
  "homepage": "URL of the data publisher"
}
----

== Supported Datasets

By default, the following datasets/formats are supported:

* https://github.com/ag-sc/QALD[*QALD:* Question Answering over Linked Data]
** format identifier: `qald`
** supported versions: 5, 6, 8, 9, 9-plus, and 10 
* https://github.com/AskNowQA/LC-QuAD[*LC-QuAD:* Largescale Complex Question Answering Dataset]
** supported versions:
*** 1, format identifier: `lc-quad`
*** 2, format identifier: `lc-quad-2`
* https://github.com/vladislavneon/RuBQ[*RuBQ:* A Russian Knowledge Base Question Answering and Machine Reading Comprehension Data Set]
** format identifier: `rubq`
** supported versions: 1 and 2
* https://www.amazon.science/publications/mintaka-a-complex-natural-and-multilingual-dataset-for-end-to-end-question-answering[*Mintaka:* A complex, natural, and multilingual dataset for end-to-end question answering] 
** format identifier: `mintaka`
* https://www.tau-nlp.sites.tau.ac.il/compwebq[*ComplexWebQuestions:* A dataset for answering complex questions that require reasoning over multiple web snippets]
** format identifier: `cwq`

== Supported output formats
You can choose the output format of the service by providing
an `Accept Header`. The following `Content-Types` are supported:

* `text/turtle` (https://en.wikipedia.org/wiki/Turtle_(syntax)[Turtle], default)
* `text/xml` (https://en.wikipedia.org/wiki/TriX_(serialization_format)[TriX])
* `application/ld+json` (https://en.wikipedia.org/wiki/JSON-LD[JSON-LD])
* `application/n-triples` (https://en.wikipedia.org/wiki/N-Triples[N-Triples])

== Web Service Usage

The following cURL command can be used to convert a JSON file of the QALD benchmark into RDF using Turtle as the output format.

[source,bash]
----
curl --location --request POST 'http://$HOST:$PORT/json2rdf' \
--header 'Content-Type: application/json' \
--data-raw '{
    "filePath": "https://github.com/ag-sc/QALD/raw/master/6/data/qald-6-train-multilingual-raw.json",
    "format": "qald",
    "label": "QALD 6 train multilingual raw",
    "homepage": "https://github.com/ag-sc/QALD"
}'
----

== Adding additional formats

To add new mapping rules just add a new mapping file `NAME.ttl` to `app/mappings` while `NAME` has to be in all caps. 
The mapping language is https://rml.io/specs/rml/[RML]. 
To use the file within the webservice just use the base file name as the `format` parameter.


