:toc:
:toclevels: 5
:toc-placement!:
:source-highlighter: highlight.js
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]

= question-answering-dataset-RDFizer

This tool provides a web service to convert particular question answering datasets (represented in JSON format) into RDF Turtle.

toc::[]

== Setup service

=== Using Gradle

To run the service locally run `./gradlew run`.

=== Using Docker

Otherwise, you can set up a Docker image running the service by pulling the following
image:

[source,bash]
----
docker pull bigoli98/rdfizer:latest
----

Alternatively you can build the Docker image from source.
To start a Docker container use the following command:

[source,shell]
----
docker run -d -p "$EXTERNAL_PORT:8080" bigoli98/rdfizer:latest
----

== Accessing the service

To transform a JSON file to RDF perform a `POST`-Request at `$HOST:$PORT/json2rdf`
with a JSON payload of the following structure:

[source,json]
----
{
  "filePath": "URL of the JSON file",
  "format": "Mapping file name",
  "label": "Name for the generated RDF triples",
  "homepage": "URL of the data publisher"
}
----

By default, the following formats are supported (recognize the format `key`):

* https://github.com/ag-sc/QALD[*QALD:* Question Answering over Linked Data], supported versions 5, 6, 8, 9 and 10  (`qald`)
* https://github.com/AskNowQA/LC-QuAD[*LC-QuAD:* Largescale Complex Question Answering Dataset], supported version 1 (`lc-quad`) and 2 (`lc-quad-2`)
* https://github.com/vladislavneon/RuBQ[*RuBQ:* A Russian Knowledge Base Question Answering and Machine Reading Comprehension Data Set], supported versions 1 and 2 (`rubq`)
* https://www.amazon.science/publications/mintaka-a-complex-natural-and-multilingual-dataset-for-end-to-end-question-answering[*Mintaka:* A complex, natural, and multilingual dataset for end-to-end question answering] 
* https://www.tau-nlp.sites.tau.ac.il/compwebq[*ComplexWebQuestions:* A dataset for answering complex questions that require reasoning over multiple web snippets.] (`cwq`)

The following cURL command can be used to convert a JSON file of the QALD benchmark
into RDF.

[source,bash]
----
curl --location --request POST 'http://$HOST:$PORT/json2rdf' \
--header 'Content-Type: application/json' \
--data-raw '{
    "filePath": "https://github.com/ag-sc/QALD/raw/master/6/data/qald-6-train-multilingual-raw.json",
    "format": "qald",
    "label": "QALD 6 train multilingual raw",
    "homepage": "https://github.com/ag-sc/QALD"
}'
----

== Adding additional formats

To add new mapping rules just add a new mapping file `NAME.ttl` to `app/mappings` while `NAME` has to be in all caps. 
The mapping language is https://rml.io/specs/rml/[RML]. 
To use the file within the webservice just use the base file name as the `format` parameter.


