= SPARQL dataset statistics

This subproject address the need of a good understanding of the characteristics of Knowledge Graph Question Answering benchmark datasets.
For this purpose, a tool is provided here to create a Excel Spreadsheet with statistics from a triplestore, currently the https://www.stardog.com/[Stardog triplestore] is supported.
You need to install https://docs.docker.com/get-docker/[Docker]
and run the following command.

[source]
----
./createSpreadsheet.sh
----

This script creates new CSV files with all statistics
and stores it at `~/QADO-statistics/QADO-statistics-$+{statistic_name}+-$+{current_date}+.xlsx`.

== Configuration
=== Script configuration

You might edit the `config.py` to select your triplestore.

=== Statistics

Create your SPARQL queries and store them into the `queries` directory. 
The tool creates a new worksheet for each SPARQL query file.

==== Boxplot data

If you want to generate a boxplot, you need to store your query with the file ending `_boxplot.sparql`. 
Additionally, the data for the boxplot needs to be selected via `(GROUP_CONCAT(?YOUR_VARIABLE ; SEPARATOR = ",") AS ?concat)`.


== Default statistics

The tool generates per default the following statistics for RDFized QA benchmarks:

* Query length per benchmark
* Query modifiers per benchmark
* Question length per 
  - answer type and benchmark (boxplot)
  - benchmark (boxplot)
  - language and benchmark (boxplot)
* Questions per 
  - answer type
  - benchmark
  - language
  - language and benchmark
* Question type per benchmark
* Statistics of used resources inside the SPARQL queries per benchmark
